### ISSUE TITLE
File hooks fail to load on Windows v0.1.6 (Bun.build cannot find compiled .mjs)

### ISSUE THREAD

**Issue by sava-74** [XiaomiMiMo/MiMo-Code#1753]
## Description

After updating to v0.1.6, file hooks in `~/.config/mimocode/hooks/` fail to load with the following error:

```
ERROR service=plugin path=C:\Users\sava\.config\mimocode\hooks\autocommit.ts error=Cannot find module 'C:\Users\sava\.config\mimocode\hooks\autocommit.ts.1784129647495.mjs' from 'B/~BUN/root/chunk-gdwddpxd.js' failed to load file hook
```

## Root cause

v0.1.6 changed hook loading to use `Bun.build` (PR #1638). Bun.build compiles `.ts` to `.mjs` as a temporary artifact, but then tries to resolve the `.mjs` file from the **original hooks directory** instead of the build output directory. The timestamped `.mjs` file never exists at that path.

## Reproduction

1. Create any hook in `~/.config/mimocode/hooks/test.ts`:
```ts
export default {
  "tool.execute.after": async (input: any, output: any) => {
    console.log("hook fired")
  },
}
```
2. Start MiMoCode v0.1.6
3. Check logs: `~/.local/share/mimocode/log/*.log`
4. Error: `Cannot find module '...test.ts.TIMESTAMP.mjs'`

## Expected behavior

Hook loads successfully (as it did in v0.1.5).

## Environment

- MiMoCode: v0.1.6 (Windows x64)
- OS: Windows 11
- Bun: bundled (not standalone)

## Additional context

This is a regression from v0.1.5 where hooks loaded correctly. The issue appears to be in the Bun.build path resolution for the compiled output on Windows.

### MiMoCode version

v.0.1.6

### Operating System

Windows11
